Updated from generate-constraints
Fixes applied to automated upper-constraints.txt update:

Keep version specific pins where applicable.

Pin versions for packages that are not ready for updating:

- pyasn1,pyasn1_modules
- pysnmp-lextudio:
    ironic: "AttributeError: module 'pysnmp.hlapi' has no attribute 'usmHMACMD5AuthProtocol'"
- pyroute2: Neutron issues

Pins only relevant for python_version==3.10:

- backports.strenum===1.3.1

Change-Id: I5bf6d63416a68ec92ce63e1e985e6df3b7840661
Co-Authored-by: Dr. Jens Harbott <harbott@osism.tech>
Signed-off-by: OpenStack Proposal Bot <openstack-infra@lists.openstack.org>
Generated-By: openstack/project-config:playbooks/proposal/propose_update.sh