Updated from generate-constraints
held back cliff for the following traceback

Exception occurred:
  File "/home/zuul/src/opendev.org/openstack/python-openstackclient/.tox/docs/lib/python3.6/site-packages/cliff/sphinxext.py", line 245, in _load_app
    if not issubclass(cliff_app_class, app.App):
TypeError: issubclass() arg 1 must be a class

Change-Id: I9abfd6fcefc73ffc40cc43c9d228e40897846378