[CI][stable-only] Fix py311 and validate jobs
The two jobs are failing with error:

ModuleNotFoundError: No module named 'pkg_resources'

This is because recent setuptools (>=82.0.0) dropped pkg_resource
module from its source. Hence the workaround is to cap it for py311
and validate jobs.

Change-Id: I80b7aa537610ac5d35fa1b4c04f5246ec85a170e
Signed-off-by: Elod Illes <elod.illes@est.tech>