Exclude dulwich 0.19.3 from global requirements
dulwich 0.19.3 is broken due to [1],
we need to exclude this specific version
to avoid problems.

If we use this version will produce this kind of errors:

UnicodeDecodeError: 'ascii' codec can't decode
byte 0xc4 in position 48: ordinal not in range(128)

Because there are unicode characters in the setup.cfg
for this version.

[1]:  https://github.com/dulwich/dulwich/commit/1b6509fa3dbd05c458990b71fadff91af095f733

Depends-On: Icabb56b9c6b2d99d78a7e1a77f8fe7a4ea6fa0c8
Change-Id: I1f80bc81917f768e1ecb55aebdd5fc84e056b229