Exclude setuptools 24.0.0
setuptools 24.0.0 crashes on install with
  KeyError: 'processor_architecture'

See the related bugs.

Conflicts:
	global-requirements.txt

Change-Id: Id36059abb393a26a36528083927643f86f49f752
Related-Bug: #1598525
Related-Bug: #1598575
(cherry picked from commit 283109ef09d302c7ebde7fc652a6010cf44a9a2e)