Updated from generate-constraints
restricted update of iso8601
AttributeError: module 'iso8601.iso8601' has no attribute 'Utc'
restricted update of pika
Requirement.parse('pika<0.11,>=0.9'), set(['pika-pool']))

restricted update of sqlalchemy (based on past updates)
restricted update of kubernetes (based on past updates)

Change-Id: Ie9782d231de63a624d16e87087c6b2a3d999ff25