Bump pyOpenSSL to 16.2.0
The stable/newton branch is currently pinned to 16.1.0 which
currently raises the following exception when attempting to import
pyOpenSSL:

  AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

This issue is not present in stable/ocata as it has been bumped to
16.2.0 a while back.  The specific commit[1] which resolves this added
conditional checks to avoid this sort of issue specifically.

[1]: https://github.com/pyca/pyopenssl/commit/5af32d0d55f5d385e5592e00a2e574a43f0b74fb

Change-Id: Icc93fb11e19bb900396c485719908655fac75cf6