Raise pip min version to 8.0.2
7.1.0 appears to fail with:

 requirement_set.add_requirement(req)
   File "/home/zuul/src/git.openstack.org/openstack/requirements/.tox/py27-check-lc/local/lib/python2.7/site-packages/pip/req/req_set.py", line 267, in add_requirement
     return result
 UnboundLocalError: local variable 'result' referenced before assignment

Also adjust virtualenv accordingly so that its embedded pip is matching
that constraint

Change-Id: I4f14250d7e52719bdbf5476da057b414b4ba251c