Updated from generate-constraints
Fixes applied to automated upper-constraints.txt update:

Pin versions for packages that are not ready for updating:

- pyasn1,pyasn1_modules
- gabbi:
    placement: "AttributeError: 'NoneType' object has no attribute 'api'"
- infoblox-client:
    designate: |-
      [designate.plugin] Loaded plugin backend:infoblox
      [infoblox_client.connector] Cloud WAPI version detected: 2.10
      [infoblox_client.connector] Configuring session
      [urllib3.util.retry] Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
      [infoblox_client.connector] Authenticating with username and password.
      [infoblox_client.connector] SSL verification is False
      [infoblox_client.connector] Connector initialized with options: {'host': '192.0.2.1', 'username': '****', 'password': '****', 'http_pool_connections': None, 'http_pool_maxsize': None, 'wapi_version': '2.10', 'ssl_verify': None, 'cert': '****', 'key': '****'}
- pysnmp-lextudio:
    ironic: "AttributeError: module 'pysnmp.hlapi' has no attribute 'usmHMACMD5AuthProtocol'"
- testtools:
    tempest: "AttributeError: 'AttachVolumeMultiAttachTest' object has no attribute 'skip'"
- pyroute2:
    nova/os-vif: https://bugs.launchpad.net/os-vif/+bug/2109396

Pins only relevant for python_version==3.10:

- backports.strenum===1.3.1

Change-Id: I66bfcc73f1e03b61dca08e2cf3b35a581aaf7568
Co-Authored-by: Jens Harbott <harbott@osism.tech>
Signed-off-by: OpenStack Proposal Bot <openstack-infra@lists.openstack.org>
Generated-By: openstack/project-config:playbooks/proposal/propose_update.sh