Updated from generate-constraints
Keep version specific pins where applicable.

Pin versions for packages that are not ready for updating:

- pyasn1,pyasn1_modules
- gabbi:
    placement: "AttributeError: 'NoneType' object has no attribute 'api'"
- infoblox-client:
    designate: |-
      [designate.plugin] Loaded plugin backend:infoblox
      [infoblox_client.connector] Cloud WAPI version detected: 2.10
      [infoblox_client.connector] Configuring session
      [urllib3.util.retry] Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
      [infoblox_client.connector] Authenticating with username and password.
      [infoblox_client.connector] SSL verification is False
      [infoblox_client.connector] Connector initialized with options: {'host': '192.0.2.1', 'username': '****', 'password': '****', 'http_pool_connections': None, 'http_pool_maxsize': None, 'wapi_version': '2.10', 'ssl_verify': None, 'cert': '****', 'key': '****'}
- pysnmp-lextudio:
    ironic: "AttributeError: module 'pysnmp.hlapi' has no attribute 'usmHMACMD5AuthProtocol'"
- boto3, botocore, s3transfer:
    glance:
    - https://review.opendev.org/c/openstack/glance-specs/+/962248

Change-Id: I35412c12870fc6292636a0308dce55a5951e3737
Signed-off-by: OpenStack Proposal Bot <openstack-infra@lists.openstack.org>
Signed-off-by: Tony Breeds <tony@bakeyournoodle.com>
Generated-By: openstack/project-config:playbooks/proposal/propose_update.sh