Add upper limit for oslo.utils in stable/victoria
The `fnmatch` module was removed from oslo.utils in the Zed cycle, which
is now causing the Barbican docs job in stable/victoria to fail with
this error:

   exception: cannot import name 'fnmatch' from 'oslo_utils'

This patch limits the upper bound of oslo.utils in stable/victoria to
less than the first Zed release.

Change-Id: I205e07b7f158c453d38742cde27d9834c1d618e6