Skip django-pyscss 2.0.0
django-pyscss 2.0.0 attempts to import Py3K stdlib module pathlib
even on Python 2.x where it does not exist.

File "/usr/local/lib/python2.7/dist-packages/django_pyscss/compiler.py",
        line 4, in <module>
    from pathlib import PurePath
ImportError: No module named pathlib

https://github.com/fusionbox/django-pyscss/issues/33

Change-Id: I5df5baca3c5b79bfb173c4197421a7312da6ccd8