[stable-only] Fix gate by capping tox version
pep8, py38 and py3*-check-uc jobs are failing [1] on this branch for
some time. This patch caps tox version to get back the former behaviour
for the jobs and make them pass.

[1] https://zuul.opendev.org/t/openstack/build/d60a9b657513486e8bda21019e7cb589/log/job-output.txt#1155-1157

File "/home/zuul/src/opendev.org/openstack/requirements/.tox/.tox/lib/python3.8/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 310, in _ensure_meta_present
2024-01-15 11:00:35.514374 | ubuntu-focal |     dist_info = end.prepare_metadata_for_build_editable(self.meta_folder, self._wheel_config_settings).metadata
2024-01-15 11:00:35.514477 | ubuntu-focal | AttributeError: 'NoneType' object has no attribute 'metadata'

Change-Id: Ia32864c9620434fe4f139ba5c295997265cacc73
(cherry picked from commit 5ac6c3f2a9c923ec1d716680fcef06b26c467b9e)