Update the version of keyring to avoid bug
keyring 3.3 generates the following error:
    dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported:
    Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
The bug is fixed in keyring 3.4

Closes-Bug: #1242992

Conflicts:
	global-requirements.txt

Change-Id: I2fcb2f67d9d7570d8128f6a37c6930397eaa4a25
(cherry picked from commit 8f1842d2a7795c6e00726d94314d560a75304e36)