[stable-only] Upper constrain wheel to 0.34.2
wheel is not upper constrained but packaging is constrained to 16.8.
The latest wheel (0.35.0) requires packaging>=20.2. Strangely the pip
install does not fail, but later causes this error:

File "/home/zuul/.venv/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 23, in <module>
    from packaging import tags
ImportError: cannot import name tags

Change-Id: I01408d067f83eab4e23f6096893f0cefb8d08d4f